apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pr3oihia9-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pr3oihia9-go 
  name: pr3oihia9-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pr3oihia9-go 
