apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: pr3oihia9-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:f03f9c7f07edc35d015bfbe42cb6344d31b074d5@sha256:4ba4d8ab8f92fb996bc7b6c66f3d65ebc78f508d973fc88fbb29f617929fcda7
          name: container-image
